### ISSUE TITLE
New Games Support

### ISSUE THREAD

**Issue by vncsmnl** [Natalis-Git/Easy-Switch-Presence#3]
I know this is not a code issue or a bug, but I would like to request the option to add new released games.

Thank you in advance for your attention, your software is sensational

Thanks!

**Comment by Natalis-Git** [comment]
@viniciusoot 

My apologies, life has been busy since I released this project and I forgot to keep adding new games! I don't know when I will be able to go back to adding features to my app, but for the time being, I can continue to add games to it myself manually. I will try to add new game releases this weekend :)

If you have any specific games you would like to request, please name them and I can add them! (Once they are added, you don't even have to reinstall the app. It will retrieve the newest games automatically next time you start it up!)
